# Welcome to Jekyll!
#

title: Damien Fremont
email: test@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I'm Damien Fremont.
  Software Developer, 13 years XP (Vancouver, Canada).
author: Damien Fremont
keywords: blog,dev,it,web,java,js,test,cucumber
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://damienfremont.com" # the base hostname & protocol for your site, e.g. http://example.com

google_analytics_id: G-C6Z2RMBX8M

twitter_username: damien_fremont
github_username:  damienfremont
linkedin_username:  damienfremont

social:
  discord_invite: PPTjWjjm9a

funding:
  buymeacoffee: damienfremont
  paypal: damienfremont
# paypal_me: damienfremont
  paypal_donate: 5WTGL666THA58
  itchio: damienfremont

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  
permalink: /:year/:month/:day/:title
# https://jekyllrb.com/docs/pagination/
paginate: 15
paginate_path: "/posts/page:num/"

browsercolor: #000
copyright: Â© 2012-2026 Damien Fremont, All Rights Reserved

exclude: 
  - "/doc"
  - "/docs"
  - "/folder.jpg"
